### ISSUE TITLE
Any timeline for Linux support?

### ISSUE THREAD

**Issue by Anachron** [kristapsdz/slant#2]
I was happy to see `slant` as it was something I always wanted to have. 
Sadly I'm/we're using Linux on our servers and cannot make use of  this as it's `OpenBSD` only.

Do you have any timeline for Linux support? Is it something you are actively working?

**Comment by kristapsdz** [comment]
I don't use Linux myself, but looks like @Duncaen is contributing the labour.  Keep tabs!  (Closing this, meanwhile, as I don't let feature requests sit around...)
